const {test,expect}=require('@playwright/test');
const fs=require('node:fs/promises');
async function start(page,view) {
    await page.goto('/'); await expect(page.locator('.metric-card')).toHaveCount(6);
    if(view) await page.locator(`#sidebar-nav a[href="#${view}"]`).click();
}
async function downloaded(page,selector) {
    const event=page.waitForEvent('download'); await page.locator(selector).click();
    const file=await event; return {name:file.suggestedFilename(),text:await fs.readFile(await file.path(),'utf8')};
}
test('Anduril identity, original mark, clean navigation, and migrated theme',async({page})=>{
    await page.addInitScript(()=>localStorage.setItem('deproxy_theme','dark'));
    await start(page);
    await expect(page).toHaveTitle('Anduril — Intelligence');
    await expect(page.locator('.brand-wordmark')).toHaveText('Anduril');
    expect(await page.locator('img[src="assets/anduril-mark.svg"]').evaluate(el=>el.complete&&el.naturalWidth>0)).toBe(true);
    await expect(page.locator('html')).toHaveClass('dark');
    await expect(page.locator('#current-page-subtitle')).toHaveCount(0);
    expect(await page.locator('body').innerText()).not.toMatch(/DeProxy|OSINT|Monitor exposure/);
    await page.locator('#theme-toggle').click();
    expect(await page.evaluate(()=>localStorage.getItem('anduril_theme'))).toBe('light');
    await page.locator('button[title="Alerts"]').click();
    await expect(page.locator('#current-page-title')).toHaveText('Alerts');
});
test('persona view exports evidence, links service, closes and filters identifiers',async({page})=>{
    await start(page,'personas');
    await expect(page.getByRole('button',{name:'Add Persona'})).toHaveCount(0);
    await page.locator('#persona-search').fill('4F89 A10B');
    await expect(page.locator('#personas-tbody tr')).toHaveCount(1);
    await page.locator('#personas-tbody button').click();
    const file=await downloaded(page,'#persona-export');
    expect(file.name).toBe('anduril-TA-8821-evidence.json');
    expect(JSON.parse(file.text).actor.primary_handle).toBe('IntelBroker');
    await page.locator('#persona-close').click();
    await expect(page.locator('#persona-modal')).toBeHidden();
    await page.locator('#personas-tbody button').click();
    await page.keyboard.press('Control+k');
    await expect(page.locator('#search-modal')).toBeVisible();
    await expect(page.locator('#modal-search-input')).toBeFocused();
    await page.keyboard.press('Escape');
    await page.locator('#personas-tbody button').click();
    await page.locator('[data-service-index]').first().click();
    await expect(page.locator('#svc-detail-panel')).toContainText('IntelBroker');
    await page.locator('#svc-detail-close').click();
    await expect(page.locator('#svc-detail-panel')).toHaveCount(0);
});
test('Discover opens actor and service dossiers from matching results',async({page})=>{
    await start(page,'discover');
    await page.locator('#discover-search').fill('USDoD');
    await page.locator('[data-result]').first().click();
    await expect(page.locator('#persona-modal h2')).toHaveText('USDoD');
    await page.keyboard.press('Escape');
    await page.locator('#sidebar-nav a[href="#discover"]').click();
    await page.locator('#discover-search').fill('194.26.29.112');
    await expect(page.locator('[data-result]')).toHaveCount(1);
    await page.locator('[data-result]').click();
    await expect(page.locator('#svc-detail-panel')).toContainText('ShinyHunters');
});
test('Reports exports actual data and prints the current brief',async({page})=>{
    await start(page,'reports');
    const csv=await downloaded(page,'#btn-download-csv');
    expect(csv.text).toContain('"IntelBroker"'); expect(csv.text).toContain('"92.4"'); expect(csv.text).toContain('"185.220.101.45"');
    const json=await downloaded(page,'#btn-download-json');
    expect(JSON.parse(json.text)).toHaveLength(5);
    await page.evaluate(()=>window.print=()=>{window.printed=true;});
    await page.locator('#btn-print-report').click();
    expect(await page.evaluate(()=>window.printed)).toBe(true);
    await page.emulateMedia({media:'print'});
    await expect(page.locator('#sidebar')).toBeHidden();
    await expect(page.locator('#report-actions')).toBeHidden();
    await expect(page.locator('#report-preview')).toContainText('IntelBroker');
});
test('alerts open dossiers, acknowledge, dismiss and retain changes',async({page})=>{
    await start(page,'alerts');
    await expect(page.locator('.alert-card')).toHaveCount(10);
    await expect(page.locator('#alert-date-filter')).toHaveCount(0);
    await page.locator('#alert-severity-filter').selectOption('HIGH');
    await expect(page.locator('.alert-card:visible')).toHaveCount(4);
    await page.locator('#alert-severity-filter').selectOption('ALL');
    await page.locator('button[title="View details"]').first().click();
    await expect(page.locator('#persona-modal')).toBeVisible();
    await page.keyboard.press('Escape');
    await page.locator('#sidebar-nav a[href="#alerts"]').click();
    await page.locator('#mark-all-read-btn').click();
    await expect(page.locator('.alert-card[data-status="New"]')).toHaveCount(0);
    await page.locator('button[title="Dismiss alert"]').first().click();
    await expect(page.locator('.alert-card')).toHaveCount(9);
    await page.reload();await expect(page.locator('.metric-card')).toHaveCount(6);
    await page.locator('#sidebar-nav a[href="#alerts"]').click();
    await expect(page.locator('.alert-card')).toHaveCount(9);
    await expect(page.locator('.alert-card[data-status="New"]')).toHaveCount(0);
});
test('watchlist add, cancel, remove and persistence use correct actor names',async({page})=>{
    await start(page,'watchlist');
    await expect(page.locator('#wl-items')).toContainText('IntelBroker');
    expect(await page.locator('#wl-items').innerText()).not.toContain('Unknown Actor');
    await page.locator('#wl-add-btn').click();await page.locator('#wl-cancel-btn').click();
    await expect(page.locator('#wl-add-form')).toBeHidden();
    await page.locator('#wl-add-btn').click();
    await page.locator('#wl-name').fill('Test entity');await page.locator('#wl-save-btn').click();
    await expect(page.locator('#wl-items')).toContainText('Test entity');
    await page.reload();await expect(page.locator('.metric-card')).toHaveCount(6);
    await page.locator('#sidebar-nav a[href="#watchlist"]').click();
    await expect(page.locator('#wl-items')).toContainText('Test entity');
    await page.locator('.wl-remove-btn').last().click();
    await expect(page.locator('#wl-items')).not.toContainText('Test entity');
    expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('anduril_watchlist')).length)).toBe(4);
});
test('scanner buttons show API results and errors using mocked requests',async({page})=>{
    await start(page,'services');
    await page.locator('#svc-status-filter').selectOption('INACTIVE');
    await expect(page.locator('#svc-table-body tr')).toHaveCount(1);
    await expect(page.locator('#svc-table-body')).toContainText('USDoD');
    await page.locator('#svc-scan-btn').click();
    await expect(page.locator('#infra-scan-input')).toBeFocused();
    await page.locator('.infra-chip').first().click();
    const target=await page.locator('#infra-scan-input').inputValue();
    expect(target).toContain('.onion');
    await page.route('**/api/scan',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({origin_attribution:{clearnet_ip:'192.0.2.10',confidence_score:85,isp:'Test ISP',country:'Test'},misconfigurations:[{type:'Test finding',severity:'LOW',description:'Sample finding'}]})}));
    await page.locator('#infra-btn-passive').click();
    await expect(page.locator('#infra-results-content')).toContainText('192.0.2.10');
    await expect(page.locator('#infra-results-content')).toContainText('Test finding');
    await page.route('**/api/scan/active',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({origin_attribution:{clearnet_ip:'192.0.2.11'},vulns:[{type:'Active result',severity:'LOW'}]})}));
    await page.locator('#infra-btn-active').click();
    await expect(page.locator('#infra-results-content')).toContainText('Active result');
    await page.unroute('**/api/scan/active');
    await page.route('**/api/scan/active',r=>r.fulfill({status:503,body:'unavailable'}));
    await page.locator('#infra-btn-active').click();
    await expect(page.locator('#infra-terminal')).toContainText('Scan failed');
    await expect(page.locator('#infra-btn-active')).toBeEnabled();
});
test('investigation details work and placeholder actions are removed',async({page})=>{
    await start(page,'investigations');
    await expect(page.locator('#btnNewInvestigation')).toHaveCount(0);
    await expect(page.locator('.inv-archive')).toHaveCount(0);
    await page.locator('.inv-view').first().click();
    await expect(page.locator('#invDetailClose')).toBeVisible();
    await page.locator('#invDetailClose').click();
    await expect(page.locator('#invDetailClose')).toHaveCount(0);
});
